//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace network.BLL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdiagrams
    {
        [Key]
        public int diagram_id { get; set; }
        public string name { get; set; }
        public int principal_id { get; set; }
        public int? version { get; set; }
        public byte[] definition { get; set; }
    }
}
