//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace network.BLL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserDetails()
        {
            this.Photoalbum = new HashSet<Photoalbum>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Firstname { get; set; }

        [DataType(DataType.Date)]
        public DateTime? DateOfBirthday { get; set; }
        public int? FamilyStatusId { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public int? ImagesId { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual FamilyStatus FamilyStatus { get; set; }
        public virtual Images Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photoalbum> Photoalbum { get; set; }
    }
}
